---
- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars

  tasks:
    - name: Install docker if needed
      shell: |
        if ! command -v docker;  then
          curl -fsSL https://get.docker.com -o get-docker.sh;
          sh get-docker.sh
        fi

    - name: Pull Docker image
      shell: docker pull urielofir/weight-tracker
    
    - name: run Docker image
      shell: docker run -d -p 0.0.0.0:8080:8080/tcp urielofir/weight-tracker
