---
- hosts: all
  become: true
  gather_facts: no
  vars_files:
    - vars

  tasks:
    - name: Install docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh;
        sh get-docker.sh

    # - name: Pull default Docker image
    #   community.docker.docker_image:
    #     name: urielofir/weight-tracker
    #     source: pull
